use serde::{Deserialize, Serialize};
use strum_macros::EnumIter;

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq, Hash, EnumIter)]
pub enum SpriteId {
    Empty,
    Hourglass,
    HourglassBow,
    HourglassSword,
    Range,
    Shield,
    Sword,
    Bow,
    Concept,
    Map,
    UnitArcher,
    UnitSwordsman,
    BuildingBase,
    BuildingTower,
    BuildingSpawnpoint,
    UnitBuilder,
    UnitPriest,
    UnitDemonPig,
    CardTower,
    CardSpawnPoint,
    CardSwordsman,
    CardRanger,
    CardPriest,
    CardDirectDamage,
    CardDemonPig,
    UnitRecklessKnight,
    UnitSpy,
    UnitStreetCriminal,
    UnitSmallCriminal,
    UnitDemonWolf,
    UnitOldSwordMaster,
    UnitElfWarrior,
    UnitHomesickWarrior,
}

impl SpriteId {
    pub fn to_path(&self) -> &'static str {
        match self {
            SpriteId::Bow => "bow.png",
            SpriteId::Concept => "concept.png",
            SpriteId::Map => "map.png",
            SpriteId::Hourglass => "hourglass.png",
            SpriteId::HourglassBow => "hourglass_bow.png",
            SpriteId::HourglassSword => "hourglass_sword.png",
            SpriteId::Range => "range.png",
            SpriteId::Shield => "shield.png",
            SpriteId::UnitArcher => "unit_archer.png",
            SpriteId::UnitSwordsman => "unit_swordsman.png",
            SpriteId::UnitPriest => "unit_priest.png",
            SpriteId::UnitBuilder => "unit_builder.png",
            SpriteId::UnitDemonPig => "unit_demon_pig.png",
            SpriteId::UnitRecklessKnight => "reckless_knight.png",
            SpriteId::UnitSpy => "spy.png",
            SpriteId::UnitStreetCriminal => "street_criminal.png",
            SpriteId::UnitSmallCriminal => "small_criminal.png",
            SpriteId::UnitDemonWolf => "demon_wolf.png",
            SpriteId::UnitOldSwordMaster => "old_sword_master.png",
            SpriteId::UnitElfWarrior => "elf_warrior.png",
            SpriteId::UnitHomesickWarrior => "homesick_warrior.png",
            SpriteId::Sword => "sword.png",
            SpriteId::Empty => "x.png",
            SpriteId::BuildingBase => "building_base.png",
            SpriteId::BuildingTower => "building_tower.png",
            SpriteId::BuildingSpawnpoint => "building_spawnpoint.png",
            SpriteId::CardPriest => "card_art/priest.jpg",
            SpriteId::CardRanger => "card_art/archer.jpg",
            SpriteId::CardSwordsman => "card_art/swordsman.jpg",
            SpriteId::CardSpawnPoint => "card_art/spawn_point.jpg",
            SpriteId::CardTower => "card_art/tower.jpg",
            SpriteId::CardDirectDamage => "card_art/direct_damage.jpg",
            SpriteId::CardDemonPig => "card_art/demon_pig.jpg",
        }
    }
}
